import argparse
import json
import os
import sys

import numpy as np
import torch
from torch_geometric.data import Data

sys.path.append(os.path.join(os.path.dirname(__file__), "src"))
from evopoint_da.data.components import StructureParser, build_knn_edges
from evopoint_da.models.module import EvoPointLitModule

AA_ORDER = [
    "ALA", "CYS", "ASP", "GLU", "PHE", "GLY", "HIS", "ILE", "LYS", "LEU",
    "MET", "ASN", "PRO", "GLN", "ARG", "SER", "THR", "VAL", "TRP", "TYR",
]
AA_TO_INDEX = {aa: i for i, aa in enumerate(AA_ORDER)}


def _parse_residue_id(full_id: str) -> tuple[str, int, str]:
    """Split parser residue_id format '<chain>_<resseq><icode>'.

    Residue IDs are generated as f"{chain}_{resseq}{icode}"; mmCIF chain IDs
    may contain underscores, so we split from the rightmost underscore to avoid
    corrupting chain/residue boundaries.
    """
    if "_" not in full_id:
        return full_id, 0, ""
    chain, raw = full_id.rsplit("_", 1)
    idx = 0
    while idx < len(raw) and (raw[idx].isdigit() or (idx == 0 and raw[idx] == "-")):
        idx += 1
    resseq = int(raw[:idx]) if idx > 0 else 0
    icode = raw[idx:].strip() if idx < len(raw) else ""
    return chain, resseq, icode[:1]


def _write_ca_pdb(output_path: str, residue_ids: list[str], residue_names: list[str], coords: np.ndarray) -> None:
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("REMARK Generated by run_Predict.py\n")
        serial = 1
        for i, (rid, resn, xyz) in enumerate(zip(residue_ids, residue_names, coords), start=1):
            chain, resseq, icode = _parse_residue_id(rid)
            atom_name = "CA"
            element = "C"
            occ = 1.00
            bfac = 0.00
            x, y, z = float(xyz[0]), float(xyz[1]), float(xyz[2])
            pdb_chain = (chain[:1] if chain else " ")
            line = (
                f"ATOM  {serial:5d} {atom_name:>4s} {resn:>3s} {pdb_chain:1s}"
                f"{resseq:4d}{icode:1s}   {x:8.3f}{y:8.3f}{z:8.3f}"
                f"{occ:6.2f}{bfac:6.2f}          {element:>2s}\n"
            )
            f.write(line)
            serial += 1
            if i < len(residue_ids):
                next_chain, _, _ = _parse_residue_id(residue_ids[i])
                if next_chain != chain:
                    f.write("TER\n")
        f.write("END\n")


def _select_chain(chains: dict, chain_id: str | None):
    if chain_id is not None:
        if chain_id not in chains:
            raise ValueError(f"Requested chain_id={chain_id} not found. Available: {list(chains.keys())}")
        return chain_id, chains[chain_id]
    best_id = max(chains.keys(), key=lambda cid: len(chains[cid]["coords"]))
    return best_id, chains[best_id]


def _build_auto_features(parsed: dict, expected_in: int) -> torch.Tensor:
    """Build residue-wise fallback features directly from input structure.

    Feature blocks (before pad/trim):
      - AA one-hot (20)
      - pLDDT (1, normalized to [0,1] if values look like [0,100])
      - normalized CA coordinates (3)
    """
    residue_names = parsed.get("residue_names", [])
    plddts = np.asarray(parsed.get("plddts", []), dtype=np.float32)
    coords = np.asarray(parsed.get("coords", []), dtype=np.float32)

    n = int(coords.shape[0])
    aa_onehot = np.zeros((n, len(AA_ORDER)), dtype=np.float32)
    for i, resname in enumerate(residue_names[:n]):
        idx = AA_TO_INDEX.get(str(resname).upper())
        if idx is not None:
            aa_onehot[i, idx] = 1.0

    plddt_col = plddts[:n].reshape(n, 1) if plddts.size else np.zeros((n, 1), dtype=np.float32)
    if plddt_col.max(initial=0.0) > 1.5:
        plddt_col = plddt_col / 100.0

    if n > 0:
        coord_mean = coords.mean(axis=0, keepdims=True)
        coord_std = coords.std(axis=0, keepdims=True) + 1e-6
        coord_norm = (coords - coord_mean) / coord_std
    else:
        coord_norm = np.zeros((0, 3), dtype=np.float32)

    base = np.concatenate([aa_onehot, plddt_col, coord_norm], axis=1)

    if base.shape[1] < expected_in:
        pad = np.zeros((n, expected_in - base.shape[1]), dtype=np.float32)
        base = np.concatenate([base, pad], axis=1)
    elif base.shape[1] > expected_in:
        base = base[:, :expected_in]

    return torch.from_numpy(base).float()




def _build_prediction_report(args, selected_chain_id: str, qhat: float, reject: bool, expected_in: int, observed_in: int, pred_norm: np.ndarray, safe_center: np.ndarray) -> dict:
    pred_stats = {
        "count": int(len(pred_norm)),
        "mean_abs_dr": float(pred_norm.mean()) if len(pred_norm) else 0.0,
        "median_abs_dr": float(np.median(pred_norm)) if len(pred_norm) else 0.0,
        "p90_abs_dr": float(np.percentile(pred_norm, 90)) if len(pred_norm) else 0.0,
        "max_abs_dr": float(pred_norm.max()) if len(pred_norm) else 0.0,
    }

    report = {
        "input": {
            "pdb_file": args.pdb_file,
            "feature_pt": args.feature_pt,
            "conformal_stats": args.conformal_stats,
            "selected_chain": selected_chain_id,
            "k": int(args.k),
            "device": args.device,
        },
        "model": {
            "ckpt_path": args.ckpt_path,
            "feature_dim_observed": int(observed_in),
            "feature_dim_expected": int(expected_in),
        },
        "conformal": {
            "qhat": float(qhat),
            "reject_threshold": float(args.reject_threshold),
            "decision": "REJECT" if reject else "ACCEPT",
            "safety_radius": float(qhat),
        },
        "prediction_summary": pred_stats,
        "preview": {
            "safe_center_first5": safe_center[:5].tolist(),
        },
        "artifacts": {
            "output_pdb": args.output_pdb,
            "save_auto_feature_pt": args.save_auto_feature_pt,
        },
    }
    return report


def _print_prediction_report(report: dict) -> None:
    print("\n=== Prediction Report ===")
    print("[Input]")
    print(f"  pdb_file: {report['input']['pdb_file']}")
    print(f"  selected_chain: {report['input']['selected_chain']}")
    print(f"  k: {report['input']['k']}, device: {report['input']['device']}")

    print("[Model]")
    print(f"  ckpt_path: {report['model']['ckpt_path']}")
    print(
        "  feature_dim: "
        f"observed={report['model']['feature_dim_observed']}, expected={report['model']['feature_dim_expected']}"
    )

    print("[Conformal]")
    print(f"  decision: {report['conformal']['decision']}")
    print(
        f"  qhat={report['conformal']['qhat']:.4f}, "
        f"threshold={report['conformal']['reject_threshold']:.4f}, "
        f"safety_radius={report['conformal']['safety_radius']:.4f}"
    )

    print("[Prediction Summary]")
    ps = report["prediction_summary"]
    print(f"  nodes: {ps['count']}")
    print(f"  mean|Δr|: {ps['mean_abs_dr']:.4f}")
    print(f"  median|Δr|: {ps['median_abs_dr']:.4f}")
    print(f"  p90|Δr|: {ps['p90_abs_dr']:.4f}")
    print(f"  max|Δr|: {ps['max_abs_dr']:.4f}")
    print("  first5_safe_centers:")
    print(np.array(report["preview"]["safe_center_first5"]))

def get_args():
    p = argparse.ArgumentParser(description="Predict Δr with conformal reject option.")
    p.add_argument("--pdb_file", required=True)
    p.add_argument(
        "--feature_pt",
        default=None,
        help="Prepared graph feature file with x tensor. If omitted, features are auto-built from pdb_file.",
    )
    p.add_argument("--save_auto_feature_pt", default=None, help="Optional path to save auto-built feature payload (.pt).")
    p.add_argument("--ckpt_path", required=True)
    p.add_argument(
        "--conformal_stats",
        required=True,
        help="JSON file generated by `python -m evopoint_da.pipeline.eval_run`",
    )
    p.add_argument("--reject_threshold", type=float, default=5.0, help="Reject if qhat exceeds this threshold")
    p.add_argument("--k", type=int, default=16)
    p.add_argument("--chain_id", default=None, help="Optional chain ID to predict. Default: longest chain.")
    p.add_argument("--output_pdb", default=None, help="Optional output path for predicted CA-only PDB.")
    p.add_argument("--report_json", default=None, help="Optional path to save a detailed prediction report JSON.")
    p.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    return p.parse_args()


def main():
    args = get_args()
    parser = StructureParser()
    parsed_chains = parser.parse_ca_structure(args.pdb_file)
    if not parsed_chains:
        raise ValueError("Failed to parse input structure")
    selected_chain_id, parsed = _select_chain(parsed_chains, args.chain_id)

    pos = torch.tensor(parsed["coords"], dtype=torch.float32)

    # Torch 2.6 defaults torch.load(weights_only=True); Lightning checkpoints
    # can include OmegaConf objects, so force full checkpoint loading.
    model = EvoPointLitModule.load_from_checkpoint(args.ckpt_path, map_location=args.device, weights_only=False)
    model.eval().to(args.device)
    expected_in = int(model.hparams.in_channels)

    if args.feature_pt:
        feat = torch.load(args.feature_pt, weights_only=False)
        x = feat["x"].float()
    else:
        x = _build_auto_features(parsed, expected_in)
        print(f"[info] --feature_pt not provided; auto-built features from pdb with dim={x.size(1)}")
        if args.save_auto_feature_pt:
            payload = {
                "x": x,
                "pos": pos,
                "plddt": torch.as_tensor(parsed.get("plddts", []), dtype=torch.float32).unsqueeze(1),
                "residue_ids": parsed.get("residue_ids", []),
                "sequence": parsed.get("sequence", ""),
            }
            torch.save(payload, args.save_auto_feature_pt)
            print(f"[info] Auto-built features saved to: {args.save_auto_feature_pt}")

    if x.size(0) != len(pos):
        n = min(x.size(0), len(pos))
        print(
            f"[warning] Feature length ({x.size(0)}) != selected chain length ({len(pos)}); truncating both to {n}.",
            file=sys.stderr,
        )
        x = x[:n]
        pos = pos[:n]

    edge_index, edge_attr = build_knn_edges(pos, k=args.k)
    data = Data(x=x, pos=pos, edge_index=edge_index, edge_attr=edge_attr).to(args.device)

    if x.size(1) != expected_in:
        raise ValueError(f"Feature dim drift: input feature_dim={x.size(1)} but checkpoint expects in_channels={expected_in}")

    with open(args.conformal_stats, "r", encoding="utf-8") as f:
        stats = json.load(f)
    qhat = float(stats["qhat"])

    with torch.no_grad():
        delta = model.predict_displacement(data)
    pred_norm = torch.norm(delta, dim=-1).detach().cpu().numpy()

    reject = qhat > args.reject_threshold
    if reject:
        safe_center = pos.cpu().numpy()
        print(f"REJECT: qhat={qhat:.4f} > threshold={args.reject_threshold:.4f}; keeping original structure")
    else:
        safe_center = (pos.to(delta.device) + delta).detach().cpu().numpy()
        print(f"ACCEPT: qhat={qhat:.4f}; returning predicted structure with conformal safety sphere")

    report = _build_prediction_report(
        args=args,
        selected_chain_id=selected_chain_id,
        qhat=qhat,
        reject=reject,
        expected_in=expected_in,
        observed_in=x.size(1),
        pred_norm=pred_norm,
        safe_center=safe_center,
    )
    _print_prediction_report(report)

    if args.report_json:
        os.makedirs(os.path.dirname(args.report_json) or ".", exist_ok=True)
        with open(args.report_json, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2)
        print(f"Detailed report JSON written to: {args.report_json}")

    if args.output_pdb:
        residue_ids = list(parsed.get("residue_ids", []))[: len(safe_center)]
        residue_names = list(parsed.get("residue_names", []))[: len(safe_center)]
        _write_ca_pdb(args.output_pdb, residue_ids, residue_names, safe_center)
        print(f"Predicted PDB written to: {args.output_pdb}")


if __name__ == "__main__":
    main()
