import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np
import torch
from torch_geometric.data import Data

sys.path.append(os.path.join(os.path.dirname(__file__), "src"))
from evopoint_da.data.graph import build_knn_edges
from evopoint_da.data.structure import StructureParser, parse_residue_id, select_chain
from evopoint_da.models.module import EvoPointLitModule
from evopoint_da.pipeline.run_faspr_openmm_relax import (
    _run_faspr,
    _run_openmm_restrained_minimization,
    _write_guardrailed_pdb,
)
from evopoint_da.utils.binning import build_bin_ranges as _build_bin_ranges

AA_ORDER = [
    "ALA", "CYS", "ASP", "GLU", "PHE", "GLY", "HIS", "ILE", "LYS", "LEU",
    "MET", "ASN", "PRO", "GLN", "ARG", "SER", "THR", "VAL", "TRP", "TYR",
]
AA_TO_INDEX = {aa: i for i, aa in enumerate(AA_ORDER)}


def _summarize_prediction_bins(pred_norm: np.ndarray, edges: list[float]) -> dict[str, dict]:
    bin_stats: dict[str, dict] = {}
    total = int(len(pred_norm))
    for low, high, suffix in _build_bin_ranges(edges):
        if high is None:
            mask = pred_norm >= low
            label = f">={low:g}"
        else:
            mask = (pred_norm >= low) & (pred_norm < high)
            label = f"[{low:g}, {high:g})"
        values = pred_norm[mask]
        count = int(values.shape[0])
        bin_stats[suffix] = {
            "label": label,
            "count": count,
            "ratio": (count / total) if total > 0 else 0.0,
            "mean_abs_dr": float(values.mean()) if count > 0 else None,
            "median_abs_dr": float(np.median(values)) if count > 0 else None,
            "p90_abs_dr": float(np.percentile(values, 90)) if count > 0 else None,
            "max_abs_dr": float(values.max()) if count > 0 else None,
        }
    return bin_stats


def _write_ca_pdb(output_path: str, residue_ids: list[str], residue_names: list[str], coords: np.ndarray) -> None:
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("REMARK Generated by run_Predict.py\n")
        serial = 1
        for i, (rid, resn, xyz) in enumerate(zip(residue_ids, residue_names, coords), start=1):
            chain, resseq, icode = parse_residue_id(rid)
            atom_name = "CA"
            element = "C"
            occ = 1.00
            bfac = 0.00
            x, y, z = float(xyz[0]), float(xyz[1]), float(xyz[2])
            pdb_chain = (chain[:1] if chain else " ")
            line = (
                f"ATOM  {serial:5d} {atom_name:>4s} {resn:>3s} {pdb_chain:1s}"
                f"{resseq:4d}{icode:1s}   {x:8.3f}{y:8.3f}{z:8.3f}"
                f"{occ:6.2f}{bfac:6.2f}          {element:>2s}\n"
            )
            f.write(line)
            serial += 1
            if i < len(residue_ids):
                next_chain, _, _ = parse_residue_id(residue_ids[i])
                if next_chain != chain:
                    f.write("TER\n")
        f.write("END\n")


def _build_auto_features(parsed: dict, expected_in: int) -> torch.Tensor:
    """Build residue-wise fallback features directly from input structure.

    Feature blocks (before pad/trim):
      - AA one-hot (20)
      - pLDDT (1, normalized to [0,1] if values look like [0,100])
      - normalized CA coordinates (3)
    """
    residue_names = parsed.get("residue_names", [])
    plddts = np.asarray(parsed.get("plddts", []), dtype=np.float32)
    coords = np.asarray(parsed.get("coords", []), dtype=np.float32)

    n = int(coords.shape[0])
    aa_onehot = np.zeros((n, len(AA_ORDER)), dtype=np.float32)
    for i, resname in enumerate(residue_names[:n]):
        idx = AA_TO_INDEX.get(str(resname).upper())
        if idx is not None:
            aa_onehot[i, idx] = 1.0

    plddt_col = plddts[:n].reshape(n, 1) if plddts.size else np.zeros((n, 1), dtype=np.float32)
    if plddt_col.max(initial=0.0) > 1.5:
        plddt_col = plddt_col / 100.0

    if n > 0:
        coord_mean = coords.mean(axis=0, keepdims=True)
        coord_std = coords.std(axis=0, keepdims=True) + 1e-6
        coord_norm = (coords - coord_mean) / coord_std
    else:
        coord_norm = np.zeros((0, 3), dtype=np.float32)

    base = np.concatenate([aa_onehot, plddt_col, coord_norm], axis=1)

    if base.shape[1] < expected_in:
        pad = np.zeros((n, expected_in - base.shape[1]), dtype=np.float32)
        base = np.concatenate([base, pad], axis=1)
    elif base.shape[1] > expected_in:
        base = base[:, :expected_in]

    return torch.from_numpy(base).float()


def _load_prediction_features(
    args: argparse.Namespace,
    parsed: dict,
    pos: torch.Tensor,
    expected_in: int,
) -> tuple[torch.Tensor, torch.Tensor | None, torch.Tensor | None]:
    if args.feature_pt:
        feat = torch.load(args.feature_pt, weights_only=True)
        x = feat["x"].float()
        edge_index = feat.get("edge_index", None)
        edge_attr = feat.get("edge_attr", None)
        if edge_index is not None:
            edge_index = edge_index.long()
        if edge_attr is not None:
            edge_attr = edge_attr.float()
        return x, edge_index, edge_attr

    if not getattr(args, "allow_fallback_features", False):
        raise ValueError(
            "--feature_pt is required for normal inference. The automatic fallback "
            "features are AA one-hot + pLDDT + normalized coordinates and do not "
            "match the training feature pipeline. Pass a graph feature .pt built "
            "with the same ESM/PCA + structural-feature pipeline used for training, "
            "or add --allow_fallback_features for debugging only."
        )

    x = _build_auto_features(parsed, expected_in)
    print(
        "[warning] --allow_fallback_features enabled; using debug-only fallback "
        f"features with dim={x.size(1)}. These do not match training features.",
        file=sys.stderr,
    )
    save_auto_feature_pt = getattr(args, "save_auto_feature_pt", None)
    if save_auto_feature_pt:
        payload = {
            "x": x,
            "pos": pos,
            "plddt": torch.as_tensor(parsed.get("plddts", []), dtype=torch.float32).unsqueeze(1),
            "residue_ids": parsed.get("residue_ids", []),
            "sequence": parsed.get("sequence", ""),
        }
        torch.save(payload, save_auto_feature_pt)
        print(f"[info] Auto-built fallback features saved to: {save_auto_feature_pt}")
    return x, None, None


def _feature_edges_for_node_count(
    edge_index: torch.Tensor | None,
    edge_attr: torch.Tensor | None,
    n: int,
) -> tuple[torch.Tensor | None, torch.Tensor | None]:
    if edge_index is None or edge_attr is None:
        return None, None
    if edge_index.dim() != 2 or edge_index.size(0) != 2:
        raise ValueError(f"edge_index must have shape (2, E), got {tuple(edge_index.shape)}")
    if edge_attr.dim() != 2 or edge_attr.size(0) != edge_index.size(1):
        raise ValueError(
            "edge_attr must have shape (E, edge_dim) matching edge_index; "
            f"got edge_attr={tuple(edge_attr.shape)}, edge_index={tuple(edge_index.shape)}"
        )

    if edge_index.numel() == 0:
        return edge_index.contiguous(), edge_attr.contiguous()

    valid = (
        (edge_index[0] >= 0)
        & (edge_index[1] >= 0)
        & (edge_index[0] < n)
        & (edge_index[1] < n)
    )
    if not bool(valid.all()):
        edge_index = edge_index[:, valid]
        edge_attr = edge_attr[valid]
    return edge_index.contiguous(), edge_attr.contiguous()




def _build_prediction_report(
    args,
    selected_chain_id: str,
    qhat: float,
    reject: bool,
    expected_in: int,
    observed_in: int,
    pred_norm: np.ndarray,
    safe_center: np.ndarray,
    disp_bin_edges: list[float],
) -> dict:
    pred_stats = {
        "count": int(len(pred_norm)),
        "mean_abs_dr": float(pred_norm.mean()) if len(pred_norm) else 0.0,
        "median_abs_dr": float(np.median(pred_norm)) if len(pred_norm) else 0.0,
        "p90_abs_dr": float(np.percentile(pred_norm, 90)) if len(pred_norm) else 0.0,
        "max_abs_dr": float(pred_norm.max()) if len(pred_norm) else 0.0,
    }
    pred_bin_stats = _summarize_prediction_bins(pred_norm, disp_bin_edges)

    report = {
        "input": {
            "pdb_file": args.pdb_file,
            "feature_pt": args.feature_pt,
            "allow_fallback_features": bool(getattr(args, "allow_fallback_features", False)),
            "conformal_stats": args.conformal_stats,
            "selected_chain": selected_chain_id,
            "k": int(args.k),
            "device": args.device,
        },
        "model": {
            "ckpt_path": args.ckpt_path,
            "feature_dim_observed": int(observed_in),
            "feature_dim_expected": int(expected_in),
        },
        "conformal": {
            "qhat": float(qhat),
            "reject_threshold": float(args.reject_threshold),
            "decision": "REJECT" if reject else "ACCEPT",
            "safety_radius": float(qhat),
        },
        "prediction_summary": pred_stats,
        "prediction_bins": pred_bin_stats,
        "prediction_bin_edges": [float(v) for v in disp_bin_edges],
        "preview": {
            "safe_center_first5": safe_center[:5].tolist(),
        },
        "artifacts": {
            "output_pdb": args.output_pdb,
            "save_auto_feature_pt": args.save_auto_feature_pt,
        },
    }
    return report


def _print_prediction_report(report: dict) -> None:
    print("\n=== Prediction Report ===")
    print("[Input]")
    print(f"  pdb_file: {report['input']['pdb_file']}")
    print(f"  selected_chain: {report['input']['selected_chain']}")
    print(f"  k: {report['input']['k']}, device: {report['input']['device']}")

    print("[Model]")
    print(f"  ckpt_path: {report['model']['ckpt_path']}")
    print(
        "  feature_dim: "
        f"observed={report['model']['feature_dim_observed']}, expected={report['model']['feature_dim_expected']}"
    )

    print("[Conformal]")
    print(f"  decision: {report['conformal']['decision']}")
    print(
        f"  qhat={report['conformal']['qhat']:.4f}, "
        f"threshold={report['conformal']['reject_threshold']:.4f}, "
        f"safety_radius={report['conformal']['safety_radius']:.4f}"
    )

    print("[Prediction Summary]")
    ps = report["prediction_summary"]
    print(f"  nodes: {ps['count']}")
    print(f"  mean|Δr|: {ps['mean_abs_dr']:.4f}")
    print(f"  median|Δr|: {ps['median_abs_dr']:.4f}")
    print(f"  p90|Δr|: {ps['p90_abs_dr']:.4f}")
    print(f"  max|Δr|: {ps['max_abs_dr']:.4f}")
    print("[Prediction Bin Summary]")
    print(f"  edges: {report['prediction_bin_edges']}")
    for suffix, stats in report["prediction_bins"].items():
        base = (
            f"  {suffix:>8s} {stats['label']:>10s}: "
            f"n={stats['count']}, ratio={stats['ratio']:.3f}"
        )
        if stats["count"] > 0:
            print(
                base
                + f", mean={stats['mean_abs_dr']:.4f}, median={stats['median_abs_dr']:.4f}, "
                + f"p90={stats['p90_abs_dr']:.4f}, max={stats['max_abs_dr']:.4f}"
            )
        else:
            print(base)
    print("  first5_safe_centers:")
    print(np.array(report["preview"]["safe_center_first5"]))


def _run_relax_after_prediction(
    args,
    selected_chain_id: str,
    source_center: np.ndarray,
    safe_center: np.ndarray,
) -> dict[str, str]:
    output_dir = Path(args.relax_output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    guardrailed_pdb = output_dir / "01_guardrailed_backbone.pdb"
    faspr_pdb = output_dir / "02_faspr_packed.pdb"
    minimized_pdb = output_dir / "03_openmm_minimized.pdb"

    _write_guardrailed_pdb(args.pdb_file, selected_chain_id, source_center, safe_center, str(guardrailed_pdb))
    _run_faspr(args.faspr_bin, str(guardrailed_pdb), str(faspr_pdb), args.faspr_extra_args)
    _run_openmm_restrained_minimization(
        str(faspr_pdb),
        str(minimized_pdb),
        restraint_k=args.restraint_k,
        max_iterations=args.max_iterations,
        restrain_selection=args.restrain_selection,
    )

    artifacts = {
        "guardrailed_pdb": str(guardrailed_pdb),
        "faspr_pdb": str(faspr_pdb),
        "minimized_pdb": str(minimized_pdb),
    }
    print("[relax] Finished FASPR + OpenMM relaxation.")
    print(f"[relax] Guardrailed backbone: {artifacts['guardrailed_pdb']}")
    print(f"[relax] FASPR packed:         {artifacts['faspr_pdb']}")
    print(f"[relax] OpenMM minimized:     {artifacts['minimized_pdb']}")
    return artifacts


def get_args():
    p = argparse.ArgumentParser(description="Predict Δr with conformal reject option.")
    p.add_argument("--pdb_file", required=True)
    p.add_argument(
        "--feature_pt",
        default=None,
        help=(
            "Prepared graph feature file with training-compatible x tensor. "
            "Required unless --allow_fallback_features is set for debugging."
        ),
    )
    p.add_argument(
        "--allow_fallback_features",
        action="store_true",
        help="Allow debug-only AA/pLDDT/coordinate fallback features when --feature_pt is omitted.",
    )
    p.add_argument(
        "--save_auto_feature_pt",
        default=None,
        help="Optional path to save debug-only auto-built fallback features (.pt).",
    )
    p.add_argument("--ckpt_path", required=True)
    p.add_argument(
        "--conformal_stats",
        required=True,
        help="JSON file generated by `python -m evopoint_da.pipeline.eval_run`",
    )
    p.add_argument("--reject_threshold", type=float, default=5.0, help="Reject if qhat exceeds this threshold")
    p.add_argument("--k", type=int, default=16)
    p.add_argument("--chain_id", default=None, help="Optional chain ID to predict. Default: longest chain.")
    p.add_argument("--output_pdb", default=None, help="Optional output path for predicted CA-only PDB.")
    p.add_argument("--report_json", default=None, help="Optional path to save a detailed prediction report JSON.")
    p.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    p.add_argument(
        "--run_relax",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Run FASPR + OpenMM relax right after prediction (default: enabled, disable via --no-run_relax).",
    )
    p.add_argument("--relax_output_dir", default="artifacts/relaxation", help="Output dir for relax artifacts.")
    p.add_argument("--faspr_bin", default="FASPR", help="Path to FASPR executable.")
    p.add_argument(
        "--faspr_extra_args",
        nargs="*",
        default=[],
        help="Extra args passed directly to FASPR, e.g. --faspr_extra_args -r 0",
    )
    p.add_argument("--restraint_k", type=float, default=1000.0, help="kJ/(mol*nm^2) for OpenMM restraints.")
    p.add_argument("--max_iterations", type=int, default=500, help="OpenMM minimization max iterations.")
    p.add_argument(
        "--restrain_selection",
        choices=["heavy", "ca"],
        default="heavy",
        help="Apply restraints to all heavy atoms or C-alpha atoms only.",
    )
    return p.parse_args()


def main():
    args = get_args()
    parser = StructureParser()
    parsed_chains = parser.parse_ca_structure(args.pdb_file)
    if not parsed_chains:
        raise ValueError("Failed to parse input structure")
    selected_chain_id, parsed = select_chain(parsed_chains, args.chain_id)

    pos = torch.tensor(parsed["coords"], dtype=torch.float32)

    # Torch 2.6 defaults torch.load(weights_only=True); Lightning checkpoints
    # can include OmegaConf objects, so force full checkpoint loading.
    model = EvoPointLitModule.load_from_checkpoint(args.ckpt_path, map_location=args.device, weights_only=False)
    model.eval().to(args.device)
    expected_in = int(model.hparams.in_channels)

    feature_edge_index: torch.Tensor | None
    feature_edge_attr: torch.Tensor | None
    x, feature_edge_index, feature_edge_attr = _load_prediction_features(args, parsed, pos, expected_in)

    if x.size(0) != len(pos):
        n = min(x.size(0), len(pos))
        print(
            f"[warning] Feature length ({x.size(0)}) != selected chain length ({len(pos)}); truncating both to {n}.",
            file=sys.stderr,
        )
        x = x[:n]
        pos = pos[:n]

    edge_index, edge_attr = _feature_edges_for_node_count(feature_edge_index, feature_edge_attr, len(pos))
    if edge_index is None or edge_attr is None:
        edge_index, edge_attr = build_knn_edges(pos, k=args.k)
    data = Data(x=x, pos=pos, edge_index=edge_index, edge_attr=edge_attr).to(args.device)

    if x.size(1) != expected_in:
        raise ValueError(f"Feature dim drift: input feature_dim={x.size(1)} but checkpoint expects in_channels={expected_in}")

    with open(args.conformal_stats, "r", encoding="utf-8") as f:
        stats = json.load(f)
    qhat = float(stats["qhat"])

    with torch.no_grad():
        delta = model.predict_displacement(data)
    pred_norm = torch.norm(delta, dim=-1).detach().cpu().numpy()
    model_bin_edges = getattr(model.hparams, "test_disp_bin_edges", [0.0, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0])
    disp_bin_edges = [float(v) for v in model_bin_edges]

    reject = qhat > args.reject_threshold
    if reject:
        safe_center = pos.cpu().numpy()
        print(f"REJECT: qhat={qhat:.4f} > threshold={args.reject_threshold:.4f}; keeping original structure")
    else:
        safe_center = (pos.to(delta.device) + delta).detach().cpu().numpy()
        print(f"ACCEPT: qhat={qhat:.4f}; returning predicted structure with conformal safety sphere")

    report = _build_prediction_report(
        args=args,
        selected_chain_id=selected_chain_id,
        qhat=qhat,
        reject=reject,
        expected_in=expected_in,
        observed_in=x.size(1),
        pred_norm=pred_norm,
        safe_center=safe_center,
        disp_bin_edges=disp_bin_edges,
    )
    _print_prediction_report(report)

    if args.report_json:
        os.makedirs(os.path.dirname(args.report_json) or ".", exist_ok=True)
        with open(args.report_json, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2)
        print(f"Detailed report JSON written to: {args.report_json}")

    if args.output_pdb:
        residue_ids = list(parsed.get("residue_ids", []))[: len(safe_center)]
        residue_names = list(parsed.get("residue_names", []))[: len(safe_center)]
        _write_ca_pdb(args.output_pdb, residue_ids, residue_names, safe_center)
        print(f"Predicted PDB written to: {args.output_pdb}")

    if args.run_relax:
        relax_artifacts = _run_relax_after_prediction(
            args=args,
            selected_chain_id=selected_chain_id,
            source_center=pos.detach().cpu().numpy(),
            safe_center=safe_center,
        )
        report["artifacts"]["relax"] = relax_artifacts
        if args.report_json:
            with open(args.report_json, "w", encoding="utf-8") as f:
                json.dump(report, f, indent=2)
            print(f"Detailed report JSON updated with relax artifacts: {args.report_json}")


if __name__ == "__main__":
    main()
